# Generated by Django 4.2.8 on 2023-12-26 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messages',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='receiver',
            new_name='receiver_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='sender_id',
        ),
    ]
