# Generated by Django 4.2.8 on 2023-12-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_rename_messages_message_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
